✨ Logging in with Discord
approvers/webauthn-example pull request #7
Opened 2020-11-09 13:59 UTC by siketyan

2020-11-09 14:54 UTC, MikuroXina requested changes
DTO 嫌いマンなんだけどまぁそこは許すことにする

2020-11-09 14:54 UTC, MikuroXina commented on pages/index.tsx
> +        .then()
`.then()` の意味がわからんす, 必要なのならコメントが欲しい

2020-11-09 22:29 UTC, kawaemon commented on pages/login.tsx
> +  );
（個人的にですが）とても読みにくいので、この上で
```
if (!user) {
  return (
    <Panel>
      <Spinner />
    </Panel>
  );
}
```
としておいて参考演算子を外すと読みやすくなると思います

2020-11-09 22:49 UTC, siketyan commented on pages/index.tsx
> +        .then()
Promise 無視すると IDE に怒られる

2020-11-09 22:50 UTC, siketyan commented on pages/login.tsx
> +  );
Panel を 2 回書きたくないというのがあるのでやるとしたら Inner として切り出すぐらいですかね、、、

2020-11-09 22:53 UTC, siketyan commented
@MikuroXina Model にしては薄いなって

2020-11-09 22:57 UTC, kawaemon commented on pages/login.tsx
> +  );
そうですね　それでもいいと思います、、、

2020-11-09 23:09 UTC, MikuroXina commented on pages/index.tsx
> +        .then()
その IDE の警告は無効にできないんでしょうか

2020-11-10 04:50 UTC, siketyan commented on pages/index.tsx
> +        .then()
しました…… 9f5213e

2020-11-10 04:51 UTC, siketyan commented on pages/login.tsx
> +  );
なおした 811072c

2020-11-10 05:18 UTC, MikuroXina approved these changes

2020-11-10 05:50 UTC, kawaemon approved these changes

2020-11-10 08:54 UTC, merged