✨ FaunaDB integration
approvers/webauthn-example pull request #8
Opened 2020-11-11 08:02 UTC by siketyan

FaunaDB is a database service with APIs for serverless applications.
I want to deploy this example app in serverless, so using FaunaDB is an option to persist data.

2020-11-11 13:49 UTC, MikuroXina requested changes

2020-11-11 13:49 UTC, MikuroXina commented on services/fauna/client.ts
> +      );
無理に `void` 演算子使わない方がいいかと思います
```suggestion
      await this.client.query(
        q.Update(
          this.ref(user.id),
          {
            data: user,
          },
        ),
      );
      return;
```

2020-11-11 13:49 UTC, MikuroXina commented
こうして API Routes が大きくなってくると遅くなる問題が出てくるんだけどまぁそれはそれですかね

2020-11-11 13:57 UTC, siketyan commented on services/fauna/client.ts
> +      );
なんかかっこ悪いじゃないですか……
それと return の上に 1 行空けたい派なので 2 行も増えてしまう

2020-11-11 14:13 UTC, MikuroXina commented on services/fauna/client.ts
> +      );
いろいろ考えましたが譲歩することにします

2020-11-11 14:13 UTC, MikuroXina approved these changes

2020-11-12 11:07 UTC, MikuroXina approved these changes

2020-11-12 11:48 UTC, kawaemon approved these changes

2020-11-12 14:27 UTC, MikuroXina approved these changes

2020-11-12 14:27 UTC, merged